function[m_Xd, m_Yd] = q2_applyradialdistortion(m_X, m_Y, k1, k2)

% This function will apply radial distortion provided two input matrices 'm_X' and 'm_Y' generated by the squaregrid function.
% k1 and k2 are the radial distortion parameters.
%
%
% Input:
% m_X is a q-by-r matrix
% m_Y is a q-by-r matrix
% k1 and k2 are scalars, the distortion parameters
%
% Output:
% m_Xd is a q-by-r matrix
% m_Yd is a q-by-r matrix
%
r2 = m_X.*m_X + m_Y.*m_Y;
m_Xd = m_X.*(1 + k1*r2 + k2*(r2.*r2));
m_Yd = m_Y.*(1 + k1*r2 + k2*(r2.*r2));
end